---

- name: Check for pip
  ansible.builtin.command: which pip
  register: pip_check
  failed_when: false
  no_log: true
  changed_when: false

- name: Check for pip3
  ansible.builtin.command: which pip3
  register: pip3_check
  failed_when: false
  no_log: true
  changed_when: false

- name: Download pip bootstrap
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    force: true
    mode: '0777'
  when: (pip_check is failed) or (pip3_check is failed)

- name: Install pip
  ansible.builtin.command: python get-pip.py --user
  args:
    chdir: /tmp
  when: (pip_check is failed)

- name: Install pip3
  ansible.builtin.command: python3 get-pip.py --user
  args:
    chdir: /tmp
  when: (pip3_check is failed)

- name: Clean up
  ansible.builtin.file:
    path: /tmp/get-pip.py
    state: absent
  when: (pip_check is failed) or (pip3_check is failed)
